# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: texlive/texlive:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: install zip
        run: |
          apt update
          apt install -y zip
      
      - name: install hub
        run: snap install --classic hub

      - name: generate files from dtx
        run: pdftex hpitr.dtx
      
      - name: compile all tex files with lualatex
        run: latexmk -pdf -lualatex -silent
      
      - name: create zip file for release
        run: zip hpitr.zip *.pdf *.tex README.* *.cls *.dtx
      
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: |
            "*.pdf"
            "*.tex"
            "README.*"
            "*.cls"
            "*.dtx"
            "*.zip"
      
      - name: create release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: hub release create -a "hpitr.zip#hpitr-$(sed '4q;d' README.txt | xargs |  cut -d " " -f 2)-$(date +%Y-%m-%d)" "$(sed '4q;d' README.txt | xargs |  cut -d " " -f 2)"
